### PR TITLE
- fixed (the straight line program for) a wrong class representative

### PR DESCRIPTION
**Pull request by ThomasBreuer**
I have checked that the table of marks of "2.(A4xA4).2.2" is in fact the only one in the library
for which the problem arises that the stored straight line programs are in fact not
class representatives.
For this one table of marks, the proposed change fixes the bug, by replacing one straight line program.
The general code to check this property is in a new test file.
It is called there only for the erroneous table of marks because the runtime is too large for regular automatic tests.

### CODE REVIEW

**Comment by fingolfin** [comment]
See also PR #28 :-)

**Comment by fingolfin** [comment]
@gpfeiffer @LiamNaughton it would be *really* good if you merged either this PR or PR #28 and then made a release. Or, if you are short on time, we are also happy to make that release for you. 

If it happens soon, we can get a version of tomlib with this fix into GAP 4.11.

**Comment by olexandr-konovalov** [comment]
Added this to https://github.com/gap-system/gap/issues/2984. @LiamNaughton @gpfeiffer this PR is now two months old, could you please let us know what do you think?

**Comment by olexandr-konovalov** [comment]
I think this may be closed, as the fix for the same issue was made in #28 and is now in the released version.

**Pull request closed without merging**
