### PR TITLE
PackageInfo.g: add Thomas Merkwitz as author

### LINKED ISSUE #18: list of authors in PackageInfo.g
When updating some references to GAP packages,
I noticed that Thomas Merkwitz is no longer listed as an author of the TomLib package.
Why has his name been removed?

### PR DESCRIPTION
**Pull request by fingolfin**
Resolves #18

### CODE REVIEW

**Review by gpfeiffer — CHANGES_REQUESTED** [review]
That's fine in principle.  The author was dropped by accident, misjudging the importance of this file.
However, in the current form the file isn't syntactically correct: the new author record should come before
Liam's, not within ...

**Comment by fingolfin** [comment]
Oops, quite embarrassing. Should be fixed now

**Review by gpfeiffer — APPROVED** [review]

**Review by olexandr-konovalov — APPROVED** [review]

**Comment by fingolfin** [comment]
So it would be great if my PRs were merged and then a new release was made, in time for GAP 4.11. I assume this is waiting for @LiamNaughton to also approve these PRs?

**Review by LiamNaughton — COMMENTED** [review]
All fine.

**Comment by fingolfin** [comment]
Good! What about the other PR?

**Pull request merged**
